name: CI
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  BuildBazel:
    runs-on: windows-latest
    steps:
      #- run: sudo apt install gcc
      #- run: sudo apt install build-essential
      - run: gcc --version
      - uses: jwlawson/actions-setup-bazel@v2
        with:
          bazel-version: '7.5.0'
      - uses: actions/checkout@v2
      - run: bazel build //src --cxxopt='-std=c++17'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      
