name: CI
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]
jobs:
  BuildBazel:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - uses: jwlawson/actions-setup-bazel@v2
        with:
          bazel-version: '7.5.0'
      - uses: actions/checkout@v4
      - run: bazel build //src --cxxopt='-std=c++17'
      - name: Create/ Upload Release        
        uses: softprops/action-gh-release@v1
        with: 
          files: '*.bin'
      
