name: CI
run-name: ${{ github.actor }} is building
on: push
  
jobs:
  BuildBazel:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: jwlawson/actions-setup-bazel@v2
        with:
          bazel-version: '7.5.0'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
