name: CI
run-name: ${{ github.actor }} is building
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  
jobs:
  BuildBazel:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: jwlawson/actions-setup-bazel@v2
        with:
          bazel-version: '7.5.0'
      - uses: actions/checkout@v4
      - run: bazel build //src --cxxopt='-std=c++17'
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: '*.exe'
